import {useState} from 'react';
import {ArrowUpRight, ShoppingBag, Truck, PackageCheck, ReceiptText, ArrowRight, Check} from 'lucide-react';
const usd=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export function CommerceStory(){
 const [ad,setAd]=useState(18),[returns,setReturns]=useState(5);
 const profit=100-42-8-4-6-ad-returns;
 return <>
 <section id="dropshipping" className="commerce-section landing-container">
 <div className="commerce-heading"><span className="landing-eyebrow">THE COMMERCE THESIS</span><h2>A storefront without<br/>a warehouse of your own.</h2><p>Dropshipping is a retail fulfillment model: a customer buys from a seller, and a third-party supplier sends the product directly to that customer. The seller still manages the offer, customer relationship and order outcome.</p></div>
 <div className="commerce-flow">{[
 [ShoppingBag,'01','Customer places an order','A product, a clear selling price and a delivery promise. Demand starts with a real customer.'],
 [ReceiptText,'02','Seller routes the order','The seller pays the supplier and organizes fulfillment. The difference in prices is not yet net profit.'],
 [Truck,'03','Supplier ships directly','The supplier dispatches to the buyer. Tracking, delivery quality and returns need operational oversight.'],
 [PackageCheck,'04','Costs are reconciled','After costs and obligations, any eligible profit can be funded into the settlement vault.']
 ].map(([Icon,n,title,copy])=>{const I=Icon as typeof ShoppingBag;return <article key={String(n)}><div><I size={25}/><span>{String(n)}</span></div><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div>
 <div className="commerce-bottom"><p><b>Why this model?</b> It can reduce the need to hold inventory and allow products to be tested before a larger commitment. It does not remove advertising costs, supplier risk, refunds or working-capital needs.</p><p><b>Where GLOBAL fits.</b> The intended business operates outside the blockchain. This release provides settlement accounting; it does not currently source products, accept retail orders or run fulfillment automatically.</p></div>
 </section>
 <section id="business-case" className="business-case"><div className="landing-container">
 <div className="section-heading"><div><span className="landing-eyebrow">THE ECONOMIC CASE</span><h2>Revenue is the beginning.<br/><em>Margin is the test.</em></h2></div><p>A viable operation needs repeatable demand, reliable suppliers and positive economics after all costs. No trading results or proven profitability are claimed for this project.</p></div>
 <div className="margin-grid"><div className="margin-explanation"><h3>Test the economics<br/>of one order.</h3><p>Change acquisition cost and the returns allowance to see how quickly a margin can change. These invented inputs explain the model; they are not GLOBAL operating results or a return forecast.</p><div className="margin-control"><label htmlFor="ad-cost">Customer acquisition cost <b>{usd(ad)}</b></label><input id="ad-cost" type="range" min="0" max="45" value={ad} onChange={e=>setAd(Number(e.target.value))}/><div><span>$0</span><span>$45 per order</span></div></div><div className="margin-control"><label htmlFor="return-cost">Returns & chargeback allowance <b>{usd(returns)}</b></label><input id="return-cost" type="range" min="0" max="20" value={returns} onChange={e=>setReturns(Number(e.target.value))}/><div><span>$0</span><span>$20 per order</span></div></div><p className="break-even">Break-even acquisition cost in this example: <b>{usd(40-returns)}</b> per order.</p></div>
 <div className="margin-receipt"><div className="receipt-heading"><span>ILLUSTRATIVE ORDER / USD</span><ReceiptText size={22}/></div><div className="receipt-sales"><span>Customer payment</span><strong>$100.00</strong></div><dl>{[['Product procurement',42],['Shipping & fulfillment',8],['Payment & platform costs',4],['Other costs & tax allowance',6],['Customer acquisition',ad],['Returns & chargebacks',returns]].map(([label,v])=><div key={label}><dt>{label}</dt><dd>−{usd(Number(v))}</dd></div>)}</dl><div className={'margin-total '+(profit<0?'is-loss':'')} aria-live="polite"><span>{profit<0?'Illustrative loss':'Illustrative operating surplus'}<small>Before network allocation</small></span><strong>{usd(profit)}</strong></div><p>{profit>0?`${profit}% illustrative margin. Actual reconciliation must cover all applicable expenses, taxes, refunds and unsettled obligations before a profit report.`:'No positive surplus is available in this scenario. A capital tier or referral network does not turn a loss into profit.'}</p></div></div>
 <div className="business-principles"><article><span>01 / DEMAND</span><h3>Sell what customers need.</h3><p>Validate a product and its acquisition cost before scaling spend. More sales can increase losses when each order loses money.</p></article><article><span>02 / EXECUTION</span><h3>Protect the order margin.</h3><p>Supplier quality, delivery times, refunds and fees determine whether the price difference survives fulfillment.</p></article><article><span>03 / CASH FLOW</span><h3>Keep obligations funded.</h3><p>Cash tied up outside the vault cannot meet an on-chain withdrawal. Returning principal and reporting new profit are separate actions.</p></article></div>
 </div></section>
 </>;
}
const rates=[['Starter',6,3,1.5,.5],['Basic',8,4,2,1],['Growth',10,5,2,1],['Pro',12,6,3,1],['VIP',14,7,3,1]] as const;
export function NetworkStory(){
 const [tier,setTier]=useState(0);const r=rates[tier];const total=r.slice(1).reduce<number>((a,b)=>a+Number(b),0);
 return <section id="network-plan" className="network-story landing-container"><div className="section-heading"><div><span className="landing-eyebrow">THE INCOME & NETWORK PLAN</span><h2>Sales create the pool.<br/>Rules define the split.</h2></div><p>Registration and new-member deposits create no referral commission. Four levels share a portion of the gross funded sales profit, using the seller’s tier.</p></div>
 <div className="income-paths"><article><span>01</span><h3>Seller allocation</h3><p>The seller receives funded sales profit after eligible referral shares. Unpaid shares remain with the seller.</p></article><article><span>02</span><h3>Sales-based referrals</h3><p>Eligible upstream members receive the four published commission rates. More invitations alone do not earn a milestone bonus.</p></article><article><span>03</span><h3>Performance allocation</h3><p>An authorized reporter may allocate a funded performance budget. There is no automatic monthly payout or guaranteed ranking reward.</p></article></div>
 <div className="network-lab"><div className="network-lab-intro"><span className="landing-eyebrow">FOLLOW A $100 SETTLEMENT</span><h3>One pool.<br/>Every share visible.</h3><label htmlFor="network-tier">Seller’s plan</label><select id="network-tier" value={tier} onChange={e=>setTier(Number(e.target.value))}>{rates.map((x,i)=><option key={x[0]} value={i}>{x[0]}</option>)}</select><p>Assumes all four recipients qualify. The $100 is funded sales profit, not sales revenue or a user deposit.</p></div><div className="network-distribution" aria-live="polite"><div className="seller-share"><span>SELLER’S PROFIT BALANCE</span><strong>{usd(100-total)}</strong><p>{100-total}% of the funded pool</p></div><div className="network-levels">{r.slice(1).map((v,i)=><div key={i}><span>Level {i+1}</span><strong>{usd(Number(v))}</strong><small>{v}% of gross funded profit</small></div>)}</div><div className="network-sum"><span>Total referral allocation</span><b>{usd(total)} / {total}%</b></div></div></div>
 <div className="network-eligibility"><div><Check size={19}/><p><b>Activity comes first.</b> Each recipient must be active. VIP recipients also need reporter-verified KYC. Level four requires an active VIP recipient with verified KYC.</p></div><div><Check size={19}/><p><b>Referral relationships are fixed.</b> The referrer must already be registered. Self-referrals and changing the referrer after registration are not supported.</p></div><div><Check size={19}/><p><b>Allocation is not a withdrawal.</b> The initial 5% profit-withdrawal fee, per-withdrawal cap and 72-hour cooldown still apply. The cap is 10% of cumulative external deposits plus completed reinvestments in the same asset.</p></div></div>
 <a className="landing-text-link" href="#economics">Understand withdrawal fees and limits <ArrowRight size={18}/></a>
 <div className="network-boundary"><ArrowUpRight size={22}/><p>Recorded profit remains a claim on available liquidity. The owner can withdraw all treasury cash without partner approval; neither this network nor the daily targets guarantees payment.</p></div>
 </section>;
}
